[project]
id      = "mls"
name    = "Mach Language Server"
version = "0.7.0"
src     = "src"
dep     = "dep"
target  = "native"
out     = "out/{target}/{profile}/bin/{name}{ext}"
obj     = "out/{target}/{profile}/obj"
ir      = "out/{target}/{profile}/ir"
asm     = "out/{target}/{profile}/asm"
tests   = "out/{target}/{profile}/test/{name}"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[bin.mls]
entry = "main.mach"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[deps.mach-std]
git = "https://github.com/octalide/mach-std"
ref = "branch/main"

[deps.mach]
git = "https://github.com/octalide/mach"
ref = "branch/main"
